// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orswuveheskczsgezmuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yc3d1dmVoZXNrY3pzZ2V6bXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDM5NjgsImV4cCI6MjA2NzcxOTk2OH0.van6QuJSQIHZFIHPPqNbmGRhxeQ3QB_4WVawyKgWUys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});